import{S as c,a as l,A as u}from"./assets/vendor-daf6c9c8.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&o(s)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const p=document.querySelector(".header-menubtn"),w=document.querySelector(".header-mob-menubtn"),m=document.querySelector(".header-menu"),a=document.querySelector(".header-mob-menu"),f=document.querySelector(".header-close-icon");p.addEventListener("click",()=>m.classList.toggle("header-hidden"));w.addEventListener("click",()=>a.classList.toggle("header-mob-hidden"));f.addEventListener("click",()=>a.classList.toggle("header-mob-hidden"));new c(".swiper",{direction:"horizontal",loop:!0,speed:400,spaceBetween:100});const d=document.querySelector(".reviews-box"),h=d.querySelector(".swiper-wrapper");async function v(){const i="https://portfolio-js.b.goit.study/api/reviews";try{return(await l.get(i)).data}catch(o){throw console.error("Error fetching reviews:",o),o}}async function y(){try{const t=await v();if(!t||t.length===0){d.innerHTML='<p class="review-error">Not found</p>';return}const n=t.map(({_id:o,author:e,avatar_url:r,review:s})=>`
                <li class="review-item swiper-slide">
                <div class="review-swiper-window ">    
                <div class="review-photo">
                        <img src="${r}" alt='${e}' class="avatar">
                    </div>
                    <div class="review-content">
                        <h3 class="review-author">${e}</h3>
                        <p class="review-text">${s}</p>
                    </div>
                    </div>
                </li>`).join("");h.innerHTML=n;const i=new c(".reviews-box",{direction:"horizontal",loop:!1,speed:400,slidesPerView:1,spaceBetween:16,navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"},keyboard:{enabled:!0,onlyInViewport:!0},breakpoints:{768:{slidesPerView:2},1440:{slidesPerView:4}}})}catch(t){alert("Error rendering reviews"),console.error("Error rendering reviews:",t)}}y();new u(".accordion-container",{duration:250,showMultiple:!0});
//# sourceMappingURL=commonHelpers.js.map
