import{S as p,A as w,a as S,i as E}from"./assets/vendor-9bc83c7d.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&o(l)}).observe(document,{childList:!0,subtree:!0});function n(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(t){if(t.ep)return;t.ep=!0;const s=n(t);fetch(t.href,s)}})();const L=document.querySelector(".header-menubtn"),P=document.querySelector(".header-mob-menubtn"),q=document.querySelector(".header-menu"),v=document.querySelector(".header-mob-menu"),B=document.querySelector(".header-close-icon");L.addEventListener("click",()=>q.classList.toggle("header-hidden"));P.addEventListener("click",()=>v.classList.toggle("header-mob-hidden"));B.addEventListener("click",()=>v.classList.toggle("header-mob-hidden"));const i={projectsSection:document.querySelector("#projects"),boxArrows:document.querySelector(".swiper-box-arrows"),prevBtnProjects:document.querySelector(".swiper-prev-btn"),nextBtnProjects:document.querySelector(".swiper-next-btn")};let f=!1;function h(e,r,n){e.isBeginning?r.disabled=!0:e.isEnd?n.disabled=!0:(n.disabled=!1,r.disabled=!1)}function y(e,r){new IntersectionObserver(o=>{o.forEach(t=>{f=t.isIntersecting})},{threshold:.95}).observe(e),document.addEventListener("keydown",function(o){o.key==="Tab"&&f&&(o.preventDefault(),o.shiftKey?r.slidePrev():r.slideNext())})}function j(e,r){e.isBeginning&&(r.disabled=!0)}i.prevBtnProjects.addEventListener("click",()=>{a.slidePrev()});i.nextBtnProjects.addEventListener("click",()=>{a.slideNext()});const a=new p(".project-swiper",{direction:"horizontal",speed:1500,spaceBetween:80,centerInsufficientSlides:!0,centeredSlidesBounds:!0,grabCursor:!0,preventClicks:!0,keyboard:{enabled:!0,onlyInViewport:!0},mousewheel:{invert:!0},on:{slideChange:function(){h(this,i.prevBtnProjects,i.nextBtnProjects)}},effect:"coverflow",coverflowEffect:{rotate:30,slideShadows:!0}});j(a,i.prevBtnProjects);y(i.projectsSection,a);const b=document.querySelector(".next-slide"),u=document.querySelector(".prev-slide"),g=document.querySelector(".reviews-box"),x=g.querySelector(".reviews-list"),N=document.querySelector(".reviews-section");let c;C();async function k(){const n="https://portfolio-js.b.goit.study/api/reviews";try{return(await w.get(n)).data}catch(o){throw console.error("Error fetching reviews:",o),o}}async function C(){try{const e=await k();if(!e||e.length===0){g.innerHTML='<p class="review-error">Not found</p>';return}const r=e.map(({_id:n,author:o,avatar_url:t,review:s})=>`
                <li class="review-item swiper-slide">
                <div class="review-swiper-window "> 
     
                <div class="review-photo">
                        <img src="${t}" alt='${o}' class="avatar">
                    </div>
                    <div class="review-content">
                        <h3 class="review-author">${o}</h3>
                         <p class="review-text">${s}</p>
                    </div> 
                    </div>
                </li>`).join("");x.innerHTML=r}catch(e){alert("Error rendering reviews"),console.error("Error rendering reviews:",e)}}c=new p(".reviews-box",{direction:"horizontal",speed:400,slidesPerView:1,spaceBetween:16,keyboard:{enabled:!0,onlyInViewport:!0},mousewheel:{invert:!0},on:{slideChange:function(){h(this,u,b)}},breakpoints:{768:{slidesPerView:2},1440:{slidesPerView:4}}});c.isBeginning&&(u.disabled=!0);y(N,c);b.addEventListener("click",()=>{c.slideNext()});u.addEventListener("click",()=>{c.slidePrev()});const M=document.querySelector(".ac-trigger");new S([".container-first",".container-second"],{duration:250,showMultiple:!0});M.click();const I=w.create({baseURL:"https://portfolio-js.b.goit.study/api"}),m=document.querySelector(".footer-form"),O=document.querySelector(".footer-form-email"),A=document.querySelector(".footer-form-comment"),d=document.querySelector(".footer-modal"),D=document.querySelector(".footer-modal-close-btn-icon");async function R(e,r){try{return(await I.post("/requests",{email:e,comment:r})).data}catch(n){throw new Error(n.res.data.message)}}m.addEventListener("submit",async e=>{e.preventDefault();const r=O.value.trim(),n=A.value.trim();try{await R(r,n)&&(T(),V()),m.reset()}catch(o){E.warning({title:"WARNING",message:"Enter the correct data",position:"bottomCenter"}),console.error("Помилка:",o)}});function T(){d.classList.add("is-open")}function V(){D.addEventListener("click",()=>{d.classList.remove("is-open")})}window.addEventListener("click",e=>{e.target==d&&d.classList.remove("is-open")});
//# sourceMappingURL=commonHelpers.js.map
